/*
 * backgroundtext.frag.cg - background text fragment shader
 *
 * Copyright (C) 2016 David "Davee" Morgan
 *
 * This software may be modified and distributed under the terms
 * of the MIT license.  See the LICENSE file for details.
 */

float4 main(
	float2 vTexCoord : TEXCOORD0,
	float4 vColour : TEXCOORD1,
	uniform sampler2D tex : TEXUNIT0
)
{
	float4 c = tex2D(tex, vTexCoord);
	return float4(lerp(vColour.rgb, c.rgb, c.a), 1.f);
}