/*
 * colour.vert.cg - colour geometry vertex shader
 *
 * Copyright (C) 2016 David "Davee" Morgan
 *
 * This software may be modified and distributed under the terms
 * of the MIT license.  See the LICENSE file for details.
 */

void main(
	float3 in position,
	float4 in colour,
	uniform in float4x4 mvp,
	float4 out vPosition : POSITION,
	float4 out vColour : TEXCOORD0
)
{
	vColour = colour;
	vPosition = mul(float4(position, 1.0f), mvp);
}
